// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package com.orange;

public interface StockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.orange.Stock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ticker_symbol = 1;</code>
   */
  java.lang.String getTickerSymbol();
  /**
   * <code>string ticker_symbol = 1;</code>
   */
  com.google.protobuf.ByteString
      getTickerSymbolBytes();

  /**
   * <code>string company_name = 2;</code>
   */
  java.lang.String getCompanyName();
  /**
   * <code>string company_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
