// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package com.orange;

public interface StockQuoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.orange.StockQuote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double price = 1;</code>
   */
  double getPrice();

  /**
   * <code>int32 offer_number = 2;</code>
   */
  int getOfferNumber();

  /**
   * <code>string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
