// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package com.orange;

public final class StockQuoteProto {
  private StockQuoteProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orange_Stock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orange_Stock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orange_StockQuote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orange_StockQuote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013stock.proto\022\ncom.orange\"I\n\005Stock\022\025\n\rti" +
      "cker_symbol\030\001 \001(\t\022\024\n\014company_name\030\002 \001(\t\022" +
      "\023\n\013description\030\003 \001(\t\"F\n\nStockQuote\022\r\n\005pr" +
      "ice\030\001 \001(\001\022\024\n\014offer_number\030\002 \001(\005\022\023\n\013descr" +
      "iption\030\003 \001(\t2\245\002\n\022StockQuoteProvider\022V\n%s" +
      "erverSideStreamingGetListStockQuotes\022\021.c" +
      "om.orange.Stock\032\026.com.orange.StockQuote\"" +
      "\0000\001\022Y\n(clientSideStreamingGetStatisticsO" +
      "fStocks\022\021.com.orange.Stock\032\026.com.orange." +
      "StockQuote\"\000(\001\022\\\n)bidirectionalStreaming" +
      "GetListsStockQuotes\022\021.com.orange.Stock\032\026" +
      ".com.orange.StockQuote\"\000(\0010\001B%\n\ncom.oran" +
      "geB\017StockQuoteProtoP\001\242\002\003RTGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_orange_Stock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_orange_Stock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orange_Stock_descriptor,
        new java.lang.String[] { "TickerSymbol", "CompanyName", "Description", });
    internal_static_com_orange_StockQuote_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_orange_StockQuote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orange_StockQuote_descriptor,
        new java.lang.String[] { "Price", "OfferNumber", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
